version: "3.9"
services:
  app:
    hostname: "app"
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: "postgres"
      MONGO_HOST: "mongodb"

  postgres:
    hostname: "postgres"
    image: "postgres:13.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  mongo:
    hostname: "mongodb"
    image: "mongo"
    restart: "always"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
      MONGO_INITDB_DATABASE: "vacanpad"

  mongo-express:
    image: "mongo-express"
    restart: "always"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongodb:27017/"