"""third

Revision ID: 1c746f324814
Revises: c188ce3f4653
Create Date: 2023-02-22 21:08:19.065401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c746f324814'
down_revision = 'c188ce3f4653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_creds', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('email_creds', sa.Column('pop3_server', sa.String(length=255), nullable=True))
    op.add_column('email_creds', sa.Column('pop3_port', sa.Integer(), nullable=True))
    op.add_column('email_creds', sa.Column('imap_server', sa.String(length=255), nullable=True))
    op.add_column('email_creds', sa.Column('imap_port', sa.Integer(), nullable=True))
    op.drop_column('email_creds', 'port')
    op.drop_column('email_creds', 'pop_server')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_creds', sa.Column('pop_server', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('email_creds', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('email_creds', 'imap_port')
    op.drop_column('email_creds', 'imap_server')
    op.drop_column('email_creds', 'pop3_port')
    op.drop_column('email_creds', 'pop3_server')
    op.drop_column('email_creds', 'smtp_port')
    # ### end Alembic commands ###
