"""second

Revision ID: c188ce3f4653
Revises: 060a2c133780
Create Date: 2023-02-19 18:26:39.765798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c188ce3f4653'
down_revision = '060a2c133780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
