"""events user_id

Revision ID: f8e9e3d8c746
Revises: 1c746f324814
Create Date: 2023-03-11 22:17:50.354509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e9e3d8c746'
down_revision = '1c746f324814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_creds', 'smtp_server',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('events', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'user_id')
    op.alter_column('email_creds', 'smtp_server',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
